// category
export const GET_CATEGOEY = "GET_CATEGOEY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

// application
export const GET_APPLICATION = "GET_APPLICATION";
export const CREATE_APPLICATION = "CREATE_APPLICATION";
export const EDIT_APPLICATION = "EDIT_APPLICATION";
export const DELETE_APPLICATION = "DELETE_APPLICATION";
