// category
export const GET_CATEGORY = "GET_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

// application
export const GET_APPLICATION = "GET_APPLICATION";
export const CREATE_APPLICATION = "CREATE_APPLICATION";
export const EDIT_APPLICATION = "EDIT_APPLICATION";
export const DELETE_APPLICATION = "DELETE_APPLICATION";

// admin
export const GET_ADMIN = "GET_ADMIN";
export const CREATE_ADMIN = "CREATE_ADMIN";
export const EDIT_ADMIN = "EDIT_ADMIN";
export const DELETE_ADMIN = "DELETE_ADMIN";
